name: CI/CD CREATIVE-FRONT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        env:
            STORYBLOK_TOKEN: ${{ secrets.STORYBLOK_TOKEN }}
        run: npm run build && npm run preview

      - name: Run tests
        run: npm run test
        
       